//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanticaAutomationTestClient.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvanticaAutomationTestClient.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить рабочего.
        /// </summary>
        public static string AddWorkerAddWorker {
            get {
                return ResourceManager.GetString("AddWorkerAddWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мастер добавления рабочего.
        /// </summary>
        public static string AddWorkerAddWorkerWizzard {
            get {
                return ResourceManager.GetString("AddWorkerAddWorkerWizzard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Дата рождения.
        /// </summary>
        public static string AddWorkerBirtday {
            get {
                return ResourceManager.GetString("AddWorkerBirtday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string AddWorkerError {
            get {
                return ResourceManager.GetString("AddWorkerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский.
        /// </summary>
        public static string AddWorkerFemale {
            get {
                return ResourceManager.GetString("AddWorkerFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполите все обязательные поля!.
        /// </summary>
        public static string AddWorkerFillRequiredFields {
            get {
                return ResourceManager.GetString("AddWorkerFillRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Имя.
        /// </summary>
        public static string AddWorkerFirstName {
            get {
                return ResourceManager.GetString("AddWorkerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Есть дети?.
        /// </summary>
        public static string AddWorkerHaveChildrens {
            get {
                return ResourceManager.GetString("AddWorkerHaveChildrens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Фамилия.
        /// </summary>
        public static string AddWorkerLastName {
            get {
                return ResourceManager.GetString("AddWorkerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской.
        /// </summary>
        public static string AddWorkerMale {
            get {
                return ResourceManager.GetString("AddWorkerMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string AddWorkerMiddleName {
            get {
                return ResourceManager.GetString("AddWorkerMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string AddWorkerNo {
            get {
                return ResourceManager.GetString("AddWorkerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * - обязательный параметр.
        /// </summary>
        public static string AddWorkerRequired {
            get {
                return ResourceManager.GetString("AddWorkerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол рабочего.
        /// </summary>
        public static string AddWorkerSex {
            get {
                return ResourceManager.GetString("AddWorkerSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  успешно создан.
        /// </summary>
        public static string AddWorkerSuccessfullyCreated {
            get {
                return ResourceManager.GetString("AddWorkerSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Упс, что-то пошло не так, обратитесь к администратору.
        /// </summary>
        public static string AddWorkerTakeAdministrator {
            get {
                return ResourceManager.GetString("AddWorkerTakeAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочий .
        /// </summary>
        public static string AddWorkerWorker {
            get {
                return ResourceManager.GetString("AddWorkerWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочий добавлен.
        /// </summary>
        public static string AddWorkerWorkerSuccessfullyAdded {
            get {
                return ResourceManager.GetString("AddWorkerWorkerSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string AddWorkerYes {
            get {
                return ResourceManager.GetString("AddWorkerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить рабочего.
        /// </summary>
        public static string MainAddWorker {
            get {
                return ResourceManager.GetString("MainAddWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить рабочего?.
        /// </summary>
        public static string MainAreYouSureToDeleteWorker {
            get {
                return ResourceManager.GetString("MainAreYouSureToDeleteWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения:.
        /// </summary>
        public static string MainBirthday {
            get {
                return ResourceManager.GetString("MainBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить данные.
        /// </summary>
        public static string MainChangeWorkerData {
            get {
                return ResourceManager.GetString("MainChangeWorkerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить рабочего.
        /// </summary>
        public static string MainDeleteWorker {
            get {
                return ResourceManager.GetString("MainDeleteWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление рабочего.
        /// </summary>
        public static string MainDeletingWorker {
            get {
                return ResourceManager.GetString("MainDeletingWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский.
        /// </summary>
        public static string MainFemale {
            get {
                return ResourceManager.GetString("MainFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Есть дети:.
        /// </summary>
        public static string MainHaveChildrens {
            get {
                return ResourceManager.GetString("MainHaveChildrens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской.
        /// </summary>
        public static string MainMale {
            get {
                return ResourceManager.GetString("MainMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string MainNo {
            get {
                return ResourceManager.GetString("MainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите рабочего, которого хотите удалить!.
        /// </summary>
        public static string MainSelectDeleteWorker {
            get {
                return ResourceManager.GetString("MainSelectDeleteWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный рабочий.
        /// </summary>
        public static string MainSelectedWorker {
            get {
                return ResourceManager.GetString("MainSelectedWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения:.
        /// </summary>
        public static string MainSelectedWorkerBirthday {
            get {
                return ResourceManager.GetString("MainSelectedWorkerBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО:.
        /// </summary>
        public static string MainSelectedWorkerFLM {
            get {
                return ResourceManager.GetString("MainSelectedWorkerFLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наличие детей:.
        /// </summary>
        public static string MainSelectedWorkerHaveChildrens {
            get {
                return ResourceManager.GetString("MainSelectedWorkerHaveChildrens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол:.
        /// </summary>
        public static string MainSelectedWorkerSex {
            get {
                return ResourceManager.GetString("MainSelectedWorkerSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите рабочего, которого хотите изменить!.
        /// </summary>
        public static string MainSelectUpdateWorker {
            get {
                return ResourceManager.GetString("MainSelectUpdateWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол:.
        /// </summary>
        public static string MainSex {
            get {
                return ResourceManager.GetString("MainSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определено.
        /// </summary>
        public static string MainUndefined {
            get {
                return ResourceManager.GetString("MainUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список сотрудников.
        /// </summary>
        public static string MainWorkerList {
            get {
                return ResourceManager.GetString("MainWorkerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочий не выбран.
        /// </summary>
        public static string MainWorkerNotSelected {
            get {
                return ResourceManager.GetString("MainWorkerNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочий удалён.
        /// </summary>
        public static string MainWorkerRemoved {
            get {
                return ResourceManager.GetString("MainWorkerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочий успешно удалён!.
        /// </summary>
        public static string MainWorkerSuccessfullyRemoved {
            get {
                return ResourceManager.GetString("MainWorkerSuccessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string MainYes {
            get {
                return ResourceManager.GetString("MainYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Дата рождения.
        /// </summary>
        public static string UpdateWorkerBirthday {
            get {
                return ResourceManager.GetString("UpdateWorkerBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский.
        /// </summary>
        public static string UpdateWorkerFemale {
            get {
                return ResourceManager.GetString("UpdateWorkerFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Имя.
        /// </summary>
        public static string UpdateWorkerFirstName {
            get {
                return ResourceManager.GetString("UpdateWorkerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Есть дети?.
        /// </summary>
        public static string UpdateWorkerHaveChildrens {
            get {
                return ResourceManager.GetString("UpdateWorkerHaveChildrens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Фамилия.
        /// </summary>
        public static string UpdateWorkerLastName {
            get {
                return ResourceManager.GetString("UpdateWorkerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской.
        /// </summary>
        public static string UpdateWorkerMale {
            get {
                return ResourceManager.GetString("UpdateWorkerMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string UpdateWorkerMiddleName {
            get {
                return ResourceManager.GetString("UpdateWorkerMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string UpdateWorkerNo {
            get {
                return ResourceManager.GetString("UpdateWorkerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * - обязательный параметр.
        /// </summary>
        public static string UpdateWorkerRequired {
            get {
                return ResourceManager.GetString("UpdateWorkerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол рабочего.
        /// </summary>
        public static string UpdateWorkerSex {
            get {
                return ResourceManager.GetString("UpdateWorkerSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить рабочего.
        /// </summary>
        public static string UpdateWorkerUpdateWorker {
            get {
                return ResourceManager.GetString("UpdateWorkerUpdateWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мастер изменения рабочего.
        /// </summary>
        public static string UpdateWorkerUpdateWorkerWizzard {
            get {
                return ResourceManager.GetString("UpdateWorkerUpdateWorkerWizzard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string UpdateWorkerYes {
            get {
                return ResourceManager.GetString("UpdateWorkerYes", resourceCulture);
            }
        }
    }
}
